CREATE DATABASE note;

USE note;

CREATE TABLE users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(45) DEFAULT NULL,
  pwd VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  name VARCHAR(45) NOT NULL,
  gender VARCHAR(45) NOT NULL,
  image BLOB DEFAULT NULL,
  created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  active TINYINT(1) NULL DEFAULT 1,
  status VARCHAR(45) DEFAULT 'offline',
  PRIMARY KEY (id)
);

CREATE TABLE todos (
  id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(45) DEFAULT NULL,
  todo TEXT(200) DEFAULT NULL,
  created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  update_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  finish TINYINT(1) NULL DEFAULT 0,
  unable TINYINT(1) NULL DEFAULT 0,
  user_id INT(11) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE friends (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  date_added DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id),
  FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE notes (
  id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(45) NULL,
  note TEXT(500) NULL,
  created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  update_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  user_id INT(11) NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE groups (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE group_notes (
  id INT(11) NOT NULL AUTO_INCREMENT,
  group_id INT(11) NOT NULL,
  note_id INT(11) NOT NULL,
  time_posted DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id),
  FOREIGN KEY (group_id) REFERENCES groups(id),
  FOREIGN KEY (note_id) REFERENCES notes(id)
);
